//add your allowlists here. They need to be in the same format as you used to generate your merkle root. 
//You can also add them here and copy the route from the console log 
export const allowLists = new Map<string, Array<string>>([
  ["WL",
    [
      "Tes1zkZkXhgTaMFqVgbgvMsVkRJpq4Y6g54SbDBeKVV",
      "GjwcWFQYzemBtpUoN5fMAP2FZviTtMRWCmrppGuTthJS",
      "AT8nPwujHAD14cLojTcB1qdBzA1VXnT6LVGuUd6Y73Cy",
      "Hio2Pu5zWaT6Rm1F2wBww4zTTyKP3yzCETjgrsj8AjwS"
    ]],
  ["OGs",
    [
      "5UsfCtHpcQmEcqcmidXs3rDbPQMaf4MCXq8p5WsgG9vd",
      "Hio2Pu5zWaT6Rm1F2wBww4zTTyKP3yzCETjgrsj8AjwS",
      "5XEnUc16a4PFcqGZ85Yb59QidCE7c5yq81CkN2vtHUyd",
      "EwHcmBEPHMnWdaTqg6BdWC2N5Dz2ivww11EswQ5fe2aL",
      "GyHWBoPET9ae4YN5uioTfiPAPzSoHYQrsDViLMjJhVM4",
      "Cpvny1jUFwkAQtiCUVQFikZYBsVXu4BfsnczkHR8hnix"
    ]],
  ["default",
    [
      "Tes1zkZkXhgTaMFqVgbgvMsVkRJpq4Y6g54SbDBeKVV",
      "GjwcWFQYzemBtpUoN5fMAP2FZviTtMRWCmrppGuTthJS",
      "AT8nPwujHAD14cLojTcB1qdBzA1VXnT6LVGuUd6Y73Cy",
      "Hio2Pu5zWaT6Rm1F2wBww4zTTyKP3yzCETjgrsj8AjwS"
    ]],
  ["iferbk",
    [
      'GyHWBoPET9ae4YN5uioTfiPAPzSoHYQrsDViLMjJhVM4',
      '5UsfCtHpcQmEcqcmidXs3rDbPQMaf4MCXq8p5WsgG9vd',
      "Hio2Pu5zWaT6Rm1F2wBww4zTTyKP3yzCETjgrsj8AjwS"
    ]
  ],
  ["Free",
    [
      "E8GG8TDeXgmWZP8rT7wY69BmfoE3sAzoJFBiNWABauM6",
      "FDbaVGmubGrBFLK7Mh4dpQFs6CY2DkmykudTo95SsTEr",
      "7tXXCzAkywwjTRW92kvdPiuBpCP6s5i2yGSRuvKR4PT9",
      "3dx4gpkKfXdDKjg1TTRpxGgs71JWqzgpiKfdqongTJoM",
      "AewJnyjBhQq5ZSLzf3Tj6ca3PTWtn3sLsgygS53G3eYg",
      "kxCmxjVNZk45w7Yk3dYMpesVcc1eg8qo3tfVun2UUio",
      "83bhZQcVE9TCbGxnGCh6WVUoJhXK6sEKUz4MjGjqbVg",
      "9XCscMzW1djsytYYoMaDe7xVJFsH9vrNqbjRgnCWMNci"
    ]
  ],
]);
